### ISSUE TITLE
High Priority: Book Ownership not cross-populating

### ISSUE THREAD

**Issue by SCKaplan** [HCDigitalScholarship/booksofduchesses#3]
Instances of ownership entered into **Book model** are not cross-populating the Instance of Book Ownership field in **Owner model**, meaning that anything entered through the Book model (primary point of entry for new information) is not showing up in the appropriate libraries. 
Currently affecting 130+ books (everything entered after NE 103)

**Comment by fgould** [comment]
To try to clarify the issue: When you add a new book, and enter in information in "Ownership Information/History:", you want that data (a new DateOwned objects) to then go to the corresponding book?

It isn't possible to have the book automatically update whenever a new dateowned is added. However I can write a script to migrate over dateowned objects so that everything can be in order. With that said, that this isn't cross populating shouldn't (I think, correct me if I'm wrong) show up. Book and Owner pages all source dates from the DateOwned objects, not from their own object, so if you enter a DateOwned under an Owner, if will show up on the corresponding book's page.

Additionally, there seem to be 18 books ownership items added that did not have an owner listed, which can make them not appear. I've made all the categories mandatory to fill out, so that issue shouldn't persist. I can talk about this issue more with Sarah but I'm going to hold off action for now because (I don't think) this breaks anything.

**Comment by fgould** [comment]
I've found the bug. Book ownership events should appear in an owner's library if they were added under a book or owner regardless now.
